theme: jekyll-theme-cayman
title: "1st Data and Model Efficiency for Scalable AI Workshop"
title_html: "1st Data and Model Efficiency<br>for Scalable AI Workshop"
description: "IEEE BigData 2026 Workshop &middot; Phoenix, USA"
subtitle: "December, 2026 &middot; Precise time and date TBD"
show_downloads: false
